### PR TITLE
feat: support attributes with no value

### PR DESCRIPTION
**Pull request by nmattia**
This adds support for boolean attributes of the form `<div hidden>...`.

While not supported in XML, it seems to be officially supported by HTML:

https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

### CODE REVIEW

**Comment by nmattia** [comment]
Ran into this while playing with the crate. Not familiar with the code, hope the changes make sense!

**Comment by jdrouet** [comment]
Hey!
Thanks for that PR!
I like the idea but I'd like to keep the same logic as in the rest of the lib: just reflecting what's in the html.
From that, I mean that the attribute value, instead of creating a `"true"` that doesn't exist in the template, we should return a `Option<StrSpan<'_>>` instead of a `StrSpan<'_>`.
This would allow to support those attributes without value, without sacrificing my previous point.
That being said, this will introduce a breaking change. It's fine, it makes the library better.

**Comment by nmattia** [comment]
@jdrouet makes a ton of sense! PTAL :)

**Comment by jdrouet** [comment]
Thanks a lot @nmattia for this. I added a small function to get the potential `=`.  Will merge it when ready.

**Pull request merged**
